export const STRIP_DESIGNS = [
    { id: 'classic-white', label: 'Classic White', bg: 'bg-white', text: 'text-black' },
    { id: 'classic-black', label: 'Classic Black', bg: 'bg-zinc-950', text: 'text-white' },
    { id: 'gradient-sunset', label: 'Sunset', bg: 'bg-gradient-to-br from-orange-400 to-rose-500', text: 'text-white' },
    { id: 'gradient-ocean', label: 'Ocean', bg: 'bg-gradient-to-br from-blue-400 to-emerald-400', text: 'text-white' },
    { id: 'gradient-purple', label: 'Purple Haze', bg: 'bg-gradient-to-br from-purple-500 to-indigo-600', text: 'text-white' },
    { id: 'gradient-pink', label: 'Pink Dream', bg: 'bg-gradient-to-br from-pink-400 to-rose-400', text: 'text-white' },
    { id: 'gradient-gold', label: 'Golden Hour', bg: 'bg-gradient-to-br from-amber-200 to-yellow-500', text: 'text-black' },
    { id: 'retro', label: 'Retro', bg: 'bg-[#f4e4bc]', text: 'text-[#4a3b2a]' },
];

export const CAMERA_FILTERS = [
    { id: 'none', name: 'None', filter: 'none' },
    { id: 'grayscale', name: 'Grayscale', filter: 'grayscale(100%)' },
    { id: 'sepia', name: 'Sepia', filter: 'sepia(100%)' },
    { id: 'vintage', name: 'Vintage', filter: 'sepia(50%) contrast(110%) brightness(110%)' },
    { id: 'warm', name: 'Warm', filter: 'sepia(30%) saturate(130%) brightness(105%)' },
    { id: 'cool', name: 'Cool', filter: 'hue-rotate(180deg) saturate(120%)' },
    { id: 'dramatic', name: 'Dramatic', filter: 'contrast(150%) brightness(90%) saturate(130%)' },
    { id: 'noir', name: 'Noir', filter: 'grayscale(100%) contrast(150%) brightness(90%)' },
    { id: 'fade', name: 'Fade', filter: 'contrast(85%) brightness(110%) saturate(80%)' },
    { id: 'vivid', name: 'Vivid', filter: 'saturate(200%) contrast(110%)' },
    { id: 'pastel', name: 'Pastel', filter: 'saturate(60%) brightness(115%) contrast(90%)' },
    { id: 'retro', name: 'Retro', filter: 'sepia(40%) saturate(150%) hue-rotate(-10deg) contrast(110%)' },
    { id: 'polaroid', name: 'Polaroid', filter: 'contrast(110%) brightness(110%) saturate(130%)' },
    { id: 'nashville', name: 'Nashville', filter: 'sepia(20%) contrast(120%) brightness(105%) saturate(120%)' },
    { id: 'toaster', name: 'Toaster', filter: 'contrast(150%) brightness(90%) sepia(30%)' },
    { id: 'walden', name: 'Walden', filter: 'brightness(110%) hue-rotate(-10deg) sepia(30%) saturate(160%)' },
    { id: 'valencia', name: 'Valencia', filter: 'contrast(108%) brightness(108%) sepia(8%)' },
    { id: 'xpro', name: 'X-Pro II', filter: 'sepia(30%) contrast(130%) brightness(90%) saturate(150%)' },
    { id: 'sierra', name: 'Sierra', filter: 'contrast(110%) brightness(110%) sepia(25%) saturate(130%)' },
    { id: 'lofi', name: 'Lo-Fi', filter: 'saturate(110%) contrast(150%)' },
    { id: 'earlybird', name: 'Earlybird', filter: 'sepia(20%) contrast(110%) brightness(105%) saturate(120%)' },
    { id: 'brannan', name: 'Brannan', filter: 'sepia(50%) contrast(140%)' },
    { id: 'inkwell', name: 'Inkwell', filter: 'grayscale(100%) contrast(110%) brightness(110%)' },
    { id: 'hefe', name: 'Hefe', filter: 'contrast(110%) saturate(130%) sepia(10%)' },
    { id: 'maven', name: 'Maven', filter: 'sepia(25%) brightness(95%) contrast(95%) saturate(150%)' },
    { id: 'reyes', name: 'Reyes', filter: 'sepia(22%) brightness(110%) contrast(85%) saturate(75%)' },
    { id: 'juno', name: 'Juno', filter: 'sepia(35%) contrast(115%) brightness(115%) saturate(180%)' },
    { id: 'lark', name: 'Lark', filter: 'contrast(90%) brightness(110%) saturate(110%)' },
    { id: 'moon', name: 'Moon', filter: 'grayscale(100%) contrast(110%) brightness(110%)' },
    { id: 'clarendon', name: 'Clarendon', filter: 'contrast(120%) saturate(125%)' },
];

